### PR TITLE
Add support for showing inline blames

### LINKED ISSUE #24: GitLens like functionality
It'd be good if st3-gitblame could act similar to [GitLens](https://gitlens.amod.io) where it shows automatically for whichever line you're on.

You could also mimic some more of their functionality to show blames for different sections of code.

### LINKED ISSUE #29: Author/commiter names with more than one space not being parsed correctly
As an example:
screen shot 2018-05-23 at 10 26 30 am

It should read: 
**Git Blame** (Peter van Broekhoven) 2018-05-14 | b2d8b444 [Copy] [Show] ×

Using the ``-p`` (``--porcelain``) option I think would provide the output in a more parsable format (not sure if there's a performance hit though):
```
→ git blame -L 1484,1484 -p Something.js
b2d8b44476e48061bc50e81702fc945d11b4bc53 1394 1484 1
author Peter van Broekhoven
author-mail <...>
author-time 1526327585
author-tz -0400
committer Peter van Broekhoven
committer-mail <...>
committer-time 1526327585
committer-tz -0400
summary Commit message
previous beee2e2ab39a4fce2d8104bbade7e124e80bdc0f Something.js
filename Something.js
                    /*
```

### PR DESCRIPTION
**Pull request by psykzz**
Fixes #24 
Fixes #29 

ql9zkjwmsr

### CODE REVIEW

**Comment by jbrooksuk** [comment]
This isn't working for me at all. I'm on OSX and no console output.

**Comment by jbrooksuk** [comment]
Ah, it does work, it's just slow?

**Comment by psykzz** [comment]
@jbrooksuk I believe it may be a little slow because i use the `_async` variant.
Try removing that from the `on_selection_modified`

The downside here is causing UI jank. I'll need to make sure its performant on larger files before we can merge.

**Comment by jbrooksuk** [comment]
An option to keep this feature on by default would be 👌

**Comment by jbrooksuk** [comment]
image

Also, the phantom isn't particulary obvious on a light them.

**Comment by psykzz** [comment]
For now i just wanted to test the feature worked as expected. 
I'll need to do another pass to ensure styles work just as you pointed out.

**Comment by pvanb** [comment]
I haven't had a chance to try it yet, but it looks good from the demo. Hopefully one day there will be a way to include blank lines, but I can't remember the last time I was interested in blaming a blank line, so it's an acceptable compromise.

A couple of other comments:
- Showing blames for each line of a selection is a nice addition that I don't think GitLens has either, so 👍
- I know you're essentially re-using the same template as the command, but the "Git Blame" prefix seems uneccessary (or would be nice to be optional). It takes up valuable space when the thing of most interest is probably the name/time of the commit.
- Taking that idea further, being able to configure what info to show would be ideal (but that's probably a separate feature request)

**Comment by jbrooksuk** [comment]
> Taking that idea further, being able to configure what info to show would be ideal (but that's probably a separate feature request)

This could be done using template strings though, that'd be neat.

**Comment by psykzz** [comment]
> I know you're essentially re-using the same template as the command, but the "Git Blame" prefix seems uneccessary (or would be nice to be optional). It takes up valuable space when the thing of most interest is probably the name/time of the commit.

Sounds good.

> Taking that idea further, being able to configure what info to show would be ideal (but that's probably a separate feature request)

I agree the idea is easy but i think let's keep this PR small and have that in another PR.

**Comment by jbrooksuk** [comment]
Can we have an option to have this enabled all of the time?

**Comment by psykzz** [comment]
I don't see why not. I haven't gotten around to having settings just yet but can set that up later tonight.

**Comment by pvanb** [comment]
A couple of additional things I've noticed:

1. If I'm adding to the end of an existing line where the annotation extends beyond the window width (i.e. there's horizontal scrolling) there's a lot of flickering happening as I type with the line moving left/right. Presumably there's some position re-calculating happening?

1. If I add new lines, they show up as (Not Committed Yet) with a commit hash of 000000000000 which is as expected. However after I've committed (and pushed) the change I'm still seeing the uncommitted annotation, even after re-opening and re-toggling the inline feature.

**Comment by psykzz** [comment]
Looking for help to finish off this pull request, if anyone is interested poke me and I'll set it up.

**Comment by frou** [comment]
@psykzz Apologies, I did not notice this PR has been laying open for so long. Are you still migrated away from Sublime Text?

I'm pretty sure there will be tons of merge conflicts even after I [revert some stuff](https://github.com/frou/st3-gitblame/pull/52#issuecomment-664922813), so maybe we should just close out this PR? The diff will still be on record to refer to in future if implementing this style of feature.

**Comment by psykzz** [comment]
@frou I have yeah, pretty much migrated to VSC today. Happy to close it off. 👍

**Pull request closed without merging**
