### PR TITLE
Fixed: dont colorize diff output

### PR DESCRIPTION
**Pull request by james2doyle**

### CODE REVIEW

**Comment by frou** [comment]
Hi there - As far as I understand it, the git command-line program already automatically disables coloured output, because it can tell it's not outputting to a terminal. Am I missing something?

The colours we see when viewing the commit in Sublime Text are due to the "Diff" syntax highlighting being applied: https://github.com/frou/st3-gitblame/blob/0de97d929fac42259431e02e6bec4bdc9e7bb50c/src/blame.py#L165

**Comment by james2doyle** [comment]
I'm not familiar with the internals of git, but I have a feel that a global `.gitconfig` that contains `--color` might just apply regardless. I'm also using Fish shell so maybe there is something related there where my shell ENV is being applied. I know sublime does eval $PATH so its possible there is a hiccup there too.

Anyway, here is my original output without `--no-color`:

Screen Shot 2020-07-28 at 9 08 57 AM

You can see hidden characters in the output that stop the diff from being properly highlighted. This isnt the first time Ive encountered this issue before where there are ANSI color codes in the `git diff` output. I actually have a command in my terminal I wrote called `strip-colors` so I can copy the output of git diff and patch generation properly.

And with `--no-color`:

Screen Shot 2020-07-28 at 9 10 10 AM

You can see the hidden characters are gone and everything highlights properly.

Regardless, I can't imagine this should cause any issues right? It sounds like the default assumption is the the output shouldn’t be colorized anyway.

What do you think?

**Comment by frou** [comment]
Thanks for elaborating - That all makes sense. I actually had to do similar to your `strip-colors` when making a command to reformat the output of the Elm compiler (used [this library](https://github.com/lunixbochs/vtclean)).

It'll be a couple of days before your fix makes it out to users via Package Control, because I need to sort out `master` and tag a new version.

**Comment by frou** [comment]
The version available via Package Control now includes this fix

**Pull request merged**
